version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Baraa@1234"
      MYSQL_DATABASE: "product_order_db"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pBaraa@1234"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: productorder-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/product_order_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Baraa@1234"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
    ports:
      - "80:8080"
