name: Build & Deploy

on:
  push:
    branches: ["code-1"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_EB_APP_NAME: product-order-eb
      AWS_EB_ENV_NAME: product-order-env

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build
        run: |
          cd Backend
          mvn clean package -DskipTests

      - name: Install EB CLI
        run: |
          pip install awsebcli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EB
        run: |
          cd Backend
          eb init $AWS_EB_APP_NAME \
          --region $AWS_REGION \
          --platform "Corretto 17 running on 64bit Amazon Linux 2023"
          eb use $AWS_EB_ENV_NAME
          eb deploy --staged -nh
