name: Build & Deploy

on:
  push:
    branches: ["code-1"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build application.jar
        run: |
          cd Backend
          mvn -q -DskipTests clean package
          cp target/*.jar application.jar
          ls -lah application.jar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install CDK
        run: npm i -g aws-cdk

      - name: Install CDK deps
        run: |
          cd cdk-beanstalk
          npm ci

      - name: Deploy CDK
        run: |
          cd cdk-beanstalk
          cdk deploy --require-approval never
