name: Build & Deploy EB

on:
  push:
    branches: ["code-1"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      EB_APP_NAME: product-order-eb
      EB_ENV_NAME: product-order-env
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build JAR
        run: |
          cd Backend
          mvn clean package -DskipTests
          cp target/*.jar ../application.jar

      - name: Create ZIP bundle
        run: |
          zip app-bundle.zip application.jar
          ls -lah

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          VERSION="build-$(date +%s)"
          aws s3 cp app-bundle.zip s3://$S3_BUCKET/$VERSION.zip
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create EB App Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name $EB_APP_NAME \
            --version-label $VERSION \
            --source-bundle S3Bucket=$S3_BUCKET,S3Key=$VERSION.zip

      - name: Update EB Env
        run: |
          aws elasticbeanstalk update-environment \
            --application-name $EB_APP_NAME \
            --environment-name $EB_ENV_NAME \
            --version-label $VERSION
