name: Build & Deploy

on:
  push:
    branches: ["code-1"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build JAR
        run: |
          cd Backend
          mvn clean package -DskipTests
          cp target/*.jar app.jar

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker
        run: |
          cd Backend
          docker build -t ${{ secrets.ECR_REPO_NAME }} .
          docker tag ${{ secrets.ECR_REPO_NAME }}:latest \
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:latest
          docker push \
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:latest

      - name: Update Dockerrun Image URI
        run: |
          sed -i "s|<REPLACE_ME>|${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:latest|g" \
            cdk/eb-dockerrun/Dockerrun.aws.json

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Deploy CDK
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd cdk
          cdk deploy --require-approval never
